#!/bin/bash

CACHE=/opt/data/$ATOMIST_OWNER/$ATOMIST_REPO
if [ ! -d $CACHE ]; then
    mkdir -p $CACHE
fi

echo "Storing local Maven repository to cache"

FILE=$CACHE/maven-repository.tar.gz     
tar -zcf $FILE -C ~/.m2 repository